environment_vars:
    LIBPATH: '/usr/lpp/izoda/v110/anaconda/lib:/u/omvsadm/mvsutil/lib:/lib:/usr/lib:.'
    ZOAU_ROOT: '/usr/lpp/zoautil/v100'
    ZOAUTIL_DIR: '/usr/lpp/zoautil/v100'
    PYTHONPATH: '/usr/lpp/izoda/v110/anaconda/lib:/u/omvsadm/mvsutil/lib:/lib:/usr/lib'
    PYTHON_HOME: '/usr/lpp/izoda/v110/anaconda'
    _BPXK_JOBLOG: STDERR 
    # environment variables for mvsutils/mvscmd
    _BPXK_AUTOCVT: ON
    #_CEE_RUNOPTS: '"FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"'
    _TAG_REDIR_ERR: txt
    _TAG_REDIR_IN: txt
    _TAG_REDIR_OUT: txt
    TOOLS_ROOT: '/usr/lpp/rsusr/ported'
    PATH: '/u/omvsadm/mvsutil/bin:/usr/lpp/rsusr/ported/bin:/usr/lpp/java/java180/J8.0_64/bin:/bin:/var/bin:/usr/lpp/java/J8.0/bin:/usr/lpp/izoda/v110/anaconda/bin'
    JAVA_HOME: /usr/lpp/java/java180/J8.0_64
    STEPLIB: IMSBLD.I15RTSMM.COMRESL1