class DBDInputParameters():
    # DESTINATION = "OMVSADM.IMSTESTU.ANSIBLE.DBDLIB"
    # DESTINATION = "IMSTESTU.OMAR1.DBDLIB"
    DESTINATION = "IMSTESTU.ANSI.DBDLIB2"
    # SOURCE = "IMSTESTU.ANSIBLE.DBD.SRC"
    # SOURCE = "IMSTESTU.ANSI.DBD.SRC"
    SOURCE = "IMSTESTL.ANSIBLE.DBD.SRC"
    # SEQ_SOURCE = "OMVSADM.IMSTESTU.ANS.SEQ"
    # SEQ_SOURCE = "IMSTESTU.OMAR1.ANSI.SEQ"
    SEQ_SOURCE = "IMSTESTU.ANS.SEQ"
    # EMPTY_SEQ_SOURCE = "OMVSADM.IMSTESTU.ANS.EMPT.SEQ"
    # EMPTY_SEQ_SOURCE = "IMSTESTU.OMAR1.ANSI.EMPT.SEQ"
    EMPTY_SEQ_SOURCE = "IMSTESTU.ANS.SEQEMP"
    # FB_DESTINATION = "OMVSADM.IMSTESTU.ANSIBLE.FB.DBDLIB"
    # FB_DESTINATION = "IMSTESTU.ANSI.FB.DBDLIB"
    FB_DESTINATION = "IMSTESTU.ANSI.RECFOR"
    SYSLIB = ["IMSBLD.I15RTSMM.SDFSMAC", "SYS1.MACLIB"]
    REMOTE_DBDGEN02_SOURCE = "/tmp/dbdgen02"
    REMOTE_DBDGEN04_SOURCE = "/tmp/dbdgen04"
    LOCAL_EMPTY_SOURCE = "functional/modules/ims_dbd_gen/uss_file/data/dbdgenEmptyInput"
    DESTINATION_RF = "IMSTESTU.ANSI.RECFOR"
    # DESTINATION_RF = "IMSTESU.OMAR1.ANSI.RECFOR" 
    INVALID_SOURCE = "IMSTESTU.ANSI.INVALID"
    INVALID_USS_SOURCE = "/tmp/invalid"
    INVALID_SEQ_SOURCE = "IMSTESTU.SEQ.INVALID"
    INVALID_DESTINATION = "IMSTESTU.DBDLIB.INVALID"
    INVALID_SYSLIB = ["IMSBLD.I15RTSMM.SDFSMAC", "SYS1.INVALID"]
    
class PSBInputParameters():
    # DESTINATION = "IMSTESTU.OMAR1.PSBLIB"
    DESTINATION = "IMSTESTU.ANSI.PSBLIB2"
    # SOURCE = "IMSTESTU.ANSI.PSB.SRC"
    SOURCE = "IMSTESTL.ANSIBLE.PSB.SRC"
    SYSLIB = ["IMSBLD.I15RTSMM.SDFSMAC", "SYS1.MACLIB"]
    # DESTINATION_RF = "IMSTESU.OMAR1.ANSI.RECFOR" 
    DESTINATION_RF = "IMSTESTU.ANSI.RECFOR"
    INVALID_SOURCE = "IMSTESTU.ANSI.INVALID"
    INVALID_USS_SOURCE = "/tmp/invalid"
    INVALID_SEQ_SOURCE = "IMSTESTU.SEQ.INVALID"
    INVALID_DESTINATION = "IMSTESTU.PSBLIB.INVALID"
    INVALID_SYSLIB = ["IMSBLD.I15RTSMM.SDFSMAC", "SYS1.INVALID"]
    # FB_DESTINATION = "IMSTESTU.ANSI.FB.PSBLIB"
    FB_DESTINATION = "IMSTESTU.ANSI.RECFOR"
    # EMPTY_SEQ_SOURCE = "IMSTESTU.OMAR1.ANSI.EMPT.SEQ"
    EMPTY_SEQ_SOURCE = "IMSTESTU.ANS.SEQEMP"
    # SEQ_SOURCE = "IMSTESTU.OMAR1.ANSI.PSB.SEQ"
    SEQ_SOURCE = "IMSTESTU.ANS.PSB.SEQ"
    REMOTE_PSBGEN01_SOURCE = "/tmp/psbgen01"
    REMOTE_PSBGEN04_SOURCE = "/tmp/psbgen04"
    LOCAL_EMPTY_SOURCE = "functional/modules/ims_psb_gen/uss_file/data/psbgenEmptyInput"


class ACBInputParameters():
    JOB_CARD = """//ANSIBLE JOB 'testing',
//  CLASS=A,MSGLEVEL=(1,1),REGION=0M,
//  MSGCLASS=H,NOTIFY=&SYSUID"""

    COMMAND_INPUT_BUILD = "BUILD"
    COMMAND_INPUT_DELETE = "DELETE"
    PSBLIB = ["IMSTESTU.ANSI.PSBLIB2"]
    DBDLIB = ["IMSTESTU.ANSI.DBDLIB2"]
    ACBLIB = "IMSTESTU.ANSI.ACBLIB1"
    STEPLIB = ["IMSNEW.DIPTI.IM00.SDFSRESL"]
    RESLIB = ["IMSNEW.DIPTI.IM00.SDFSRESL"]
    PSB_NAME_ALL = "ALL"
    PSB_NAME = ["PSBGENL"]
    DBD_NAME = ["DBFSAMD3"]
    DBD_NAMES = ["DH41SK01", "HOSPVARD"]
    COMP_PRE = "PRECOMP"
    COMP_POST = "POSTCOMP"
    COMP = "PRECOMP,POSTCOMP"   
    INVALID_PSBLIB = ["INVALID.PSBLIB"]
    INVALID_DBDLIB = ["INVALID.DBDLIB"]
    INVALID_ACBLIB = ["INVALID.ACBLIB"]
    INVALID_STEPLIB = ["INVALID.SDFSRESL"]
    INVALID_RESLIB = ["INVALID.SDFSRESL"]
    INVALID_PSB = "ALL789FG*@"
    INVALID_PSBS = ["PSB1%^*#((", "PSBGENL"]
    INVALID_DBD = ["DBD1$%HJ"]
    INVALID_DBDS = ["DBFSAMD3", "DBD1$%HJ"]
    INVALID_COMP = "INVALID"