class CatalogInputParameters():
  PSBLIB = ["IMSTESTL.IMS1.PSBLIB"]
  DBDLIB = ["IMSTESTL.IMS1.DBDLIB"]
  ACBLIB = ["IMSTESTL.IMS1.ACBLIB1"]
  STEPLIB = ["IMSTESTL.IMS1. SDFSRESL"]
  PROCLIB = 'IMSTESTL.IMS1.PROCLIB'
  RESLIB = ["IMSTESTL.IMS1. SDFSRESL"]
  BUFFERPOOL = "IMSTESTL.IMS1.PROCLIB(DFSVSMHP)"
  LOADMODE = "LOAD"
  UPDATEMODE = "UPDATE"
  PRIMARYLOG = {
    "dataset_name": "IMSTESTL.IMS1.LOG",
    "disposition": "NEW",
    "normal_disposition": "DELETE"
  }