---
- name: test changes to batch option in dbd_gen
  hosts: zsystem
  environment: '{{ environment_vars }}'
  collections:
    - "ibm.ibm_zos_ims"
    - "ibm.ibm_zos_core"
  # gather_facts: no
  vars:
    SYSLIB: ["IMSBLD.I15RTSMM.SDFSMAC", "SYS1.MACLIB"]


  tasks:

  - name: basic example of ims dbdgen module with single source
    ims_dbd_gen:
      src: /tmp/dbdgen03
      location: USS
      replace: true
      dest: IMSTESTU.KETAN.DBDLIB
      sys_lib: '{{ SYSLIB }}'
 
  - name: Basic example of IMS DBDGEN module with batch input
    # register: output
    ims_dbd_gen:
      batch:
        -
          src: /tmp/dbdgen02
          location: USS
          'replace': true
        -
          src: IMSTESTU.KETAN.ANSIBLE.DBD.SRC
          member_list: [DEDBJN21]
          'replace': true
        -
          src: IMSTESTU.KETAN.SEQ.DBDSRC
          location: DATA_SET
          dbd_name: SEQ
      dest: IMSTESTU.KETAN.DBDLIB
      sys_lib: '{{SYSLIB}}'