###############################################################################
# This sample playbook demonstrates using various modules included in the
# Red Hat Ansible Certified Content for IBM Z IMS collection.
#
# Configure:
#
# Usage:
#  ansible-playbook -i <inventory> <playbook>
#
# Example:
#  ansible-playbook -i inventory ims-collection-sample.yaml
#
# Notes:
#  This sample demonstrates various ways to perform tasks using Ansible z/OS
#  IMS modules. Each module has options available on how automation can be
#  controlled. This sample does not demonstrate all options; refer to the
#  documentation or ansible-doc for those options.
#
#  When running this playbook, review the comments on how this sample will
#  interact with your destination target and ensure that you have the required
#  source and destination data sets cataloged.
#
#  There are 3 IMS modules being used in this playbook.
#
# Requirements:
#   IBM z/OS IMS collection 1.0.0 or later
#
# Configure:
#   DBDGEN:
#     src - A PDS, PDSE member, sequential data set, or USS file path.
#     member_list - A list of member names if the source specified is a data set.
#                   Is required if 'location' is 'DATA_SET' else its sequential
#                   data set.
#     destination - The target output DBDLIB partitioned data set where the DBD
#                   members will be generated.
#     sys_lib - Macro libraries that are needed to compile the DBD source.
#
#
#   PSBGEN:
#     src - A PDS, PDSE member, sequential data set, or USS file path.
#     member_list - A list of member names if the source specified is a data set.
#                   Is required if 'location' is 'DATA_SET' else its sequential
#                   data set.
#     destination - The target output PSBLIB partitioned data set where the PSB
#                   members will be generated.
#     sys_lib - Macro libraries that are needed to compile the PSB source.
#
#
#   IMS command
#     command - An IMS type-1 or type-2 command
#     plex - The target IMSplex in which the command will be submitted.
#     route - The target IMS system to run the command against.
###############################################################################

---
- hosts: all
  collections:
    - ibm.ibm_zos_ims
    - ibm.ibm_zos_core
  gather_facts: no

  environment: "{{ environment_vars }}"

  tasks:
    - name: DBDGEN
      ims_dbd_gen:
        src: IMSTESTL.ANSIBLE.DBD.SRC
        location: DATA_SET
        member_list:
          [
            DH41SK01,
            DBFSAMD1,
            DH41SK01,
            DBFSAMD2,
            DBFSAMD3,
            HOSPVARD,
            DSVNTZ30,
            DX41SK01,
            DX41SK03,
            DX41SK05,
            DX41SK06,
            DX41SK07,
            DX41SK08,
            DX41SK09,
            DX41SK02,
            DX41SK04,
          ]
        "replace": true
        dest: IMSTESTL.ANS.DBDLIB
        sys_lib:
          - IMSBLD.I15RTSMM.SDFSMAC
          - SYS1.MACLIB

    - name: PSBGEN
      ims_psb_gen:
        src: IMSTESTL.ANSIBLE.PSB.SRC
        location: DATA_SET
        member_list: [PSBGENL]
        replace: true
        dest: IMSTESTL.ANS.PSBLIB
        sys_lib:
          - IMSBLD.I15RTSMM.SDFSMAC
          - SYS1.MACLIB

    - name: ACBGEN
      ims_acb_gen:
        command_input: BUILD
        psb_name:
          - PSBGENL
        psb_lib:
          - IMSTESTL.ANS.PSBLIB
        dbd_lib:
          - IMSTESTL.ANS.DBDLIB
        acb_lib: IMSTESTL.ANS.ACBLIB
        reslib:
          - IMSTESTL.IMS1.SDFSRESL
        steplib:
          - IMSTESTL.IMS1.SDFSRESL

    - name: IMS Command
      ims_command:
        command: DISPLAY DB AUTODB
        plex: PLEX1
        route: IMS1

# ./playbook.sh playbooks/inventory playbooks/ims-collection-sample.yaml
