---
  - hosts: zsystem
    collections:
      - ibm.ibm_zos_ims
      - ibm.ibm_zos_core
    gather_facts: no
      
    environment: "{{ environment_vars }}"
      
    tasks:
      - name: test ims_catalog_purge
        ims_catalog_purge:
          reslib: IMSTESTL.IMS1.SDFSRESL
          steplib: IMSTESTL.IMS1.SDFSRESL
          proclib: IMSTESTL.IMS1.PROCLIB 
          dbd_lib: IMSTESTL.IMS1.DBDLIB
          psb_lib: IMSTESTL.IMS1.PSBLIB
          buffer_pool_param_dataset: "IMSTESTL.IMS1.PROCLIB(DFSVSMHP)"
          primary_log_dataset:
            dataset_name: IMSTESTL.IMS1.LOG1
            disposition: NEW
            normal_disposition: DELETE
            record_format: FB
            record_length: 4092
            block_size: 4096
            primary: 100
            primary_unit: CYL
            secondary: 75
            secondary_unit: CYL
            type: SEQ
          sysin:
            mode: PURGE
          sysut1:
            delete:
              - resource: DBD
                member_name: 'DB*'
                time_stamp: '*'
              - resource: DBD
                member_name: 'AUTODB'
                time_stamp: '*'
              - resource: PSB 
                member_name: 'PS*'
                time_stamp: '*'
            
  
          
          