---
- hosts: zsystem
  collections:
    - ibm.ibm_zos_ims
    - ibm.ibm_zos_core
  gather_facts: no
    
  environment: "{{ environment_vars }}"
    
  tasks:
    - name: test ims_catalog_populate
      ims_catalog_populate: 
        acb_lib: 
          [imstestl.ims1.acblib]
        psb_lib: 
          [zos.raw.test]