###############################################################################
# This sample playbook demonstrates using various modules included in the
# Red Hat Ansible Certified Content for IBM Z IMS collection.
#
# Configure:
#
# Usage:
#  ansible-playbook -i <inventory> <playbook>
#
# Example:
#  ansible-playbook -i inventory ims-collection-sample.yaml
#
# Notes:
#  This sample demonstrates various ways to perform tasks using Ansible z/OS
#  IMS modules. Each module has options available on how automation can be
#  controlled. This sample does not demonstrate all options; refer to the
#  documentation or ansible-doc for those options.
#
#  When running this playbook, review the comments on how this sample will
#  interact with your destination target and ensure that you have the required
#  source and destination data sets cataloged.
#
#  There are 3 IMS modules being used in this playbook.
#
# Requirements:
#   IBM z/OS IMS collection 1.0.0 or later
#
# Configure:
#   DBDGEN:
#     src - A PDS, PDSE member, sequential data set, or USS file path.
#     member_list - A list of member names if the source specified is a data set.
#                   Is required if 'location' is 'DATA_SET' else its sequential
#                   data set.
#     destination - The target output DBDLIB partitioned data set where the DBD
#                   members will be generated.
#     sys_lib - Macro libraries that are needed to compile the DBD source.
#
#
#   PSBGEN:
#     src - A PDS, PDSE member, sequential data set, or USS file path.
#     member_list - A list of member names if the source specified is a data set.
#                   Is required if 'location' is 'DATA_SET' else its sequential
#                   data set.
#     destination - The target output PSBLIB partitioned data set where the PSB
#                   members will be generated.
#     sys_lib - Macro libraries that are needed to compile the PSB source.
#
#
#   IMS command
#     command - An IMS type-1 or type-2 command
#     plex - The target IMSplex in which the command will be submitted.
#     route - The target IMS system to run the command against.
###############################################################################

---
  - hosts: all
    collections:
      - ibm.ibm_zos_ims
      - ibm.ibm_zos_core
    gather_facts: no

    environment: "{{ environment_vars }}"

    tasks:

      - name: test ims_catalog_populate
        ims_catalog_populate:
          mode: LOAD
          dbrc: False
          acb_lib: [
            IMSTESTL.IMS1.ACBLIB
          ]
          reslib: [
            IMSTESTL.IMS1.SDFSRESL
          ]
          steplib: [
            IMSTESTL.IMS1.SDFSRESL
          ]
          proclib: [
            IMSTESTL.IMS1.PROCLIB
          ]
          dbd_lib: [
            IMSTESTL.IMS1.DBDLIB
          ]
          psb_lib: [
            IMSTESTL.IMS1.PSBLIB
          ]
          buffer_pool_param_dataset: "IMSTESTL.IMS1.PROCLIB(DFSVSMHP)"
          primary_log_dataset:
            dataset_name: IMSTESTL.IMS1.LOG1
            disposition: NEW
            normal_disposition: DELETE
            record_format: FB
            record_length: 4092
            block_size: 4096
            primary: 100
            primary_unit: CYL
            secondary: 75
            secondary_unit: CYL
            type: SEQ
          control_statements:
            managed_acbs:
              setup: true

      - name: test ims_catalog_purge
        ims_catalog_purge:
          reslib: [
            IMSTESTL.IMS1.SDFSRESL
          ]
          steplib: [
            IMSTESTL.IMS1.SDFSRESL
          ]
          proclib: [
            IMSTESTL.IMS1.PROCLIB
          ]
          dbd_lib: [
            IMSTESTL.IMS1.DBDLIB
          ]
          psb_lib: [
            IMSTESTL.IMS1.PSBLIB
          ]
          buffer_pool_param_dataset: "IMSTESTL.IMS1.PROCLIB(DFSVSMHP)"
          primary_log_dataset:
            dataset_name: IMSTESTL.IMS1.LOG1
            disposition: NEW
            normal_disposition: DELETE
            record_format: FB
            record_length: 4092
            block_size: 4096
            primary: 100
            primary_unit: CYL
            secondary: 75
            secondary_unit: CYL
            type: SEQ
          mode: PURGE
          delete:
            - resource: DBD
              member_name: 'DB*'
              time_stamp: '*'
            - resource: DBD
              member_name: 'AUTODB'
              time_stamp: '*'
            - resource: DBD
              member_name: 'DFSCX'
              time_stamp: '*'
            - resource: DBD
              member_name: 'DI21PART'
              time_stamp: '*'
            - resource: DBD
              member_name: 'DG*'
              time_stamp: '*'
            - resource: DBD
              member_name: 'EMP*'
              time_stamp: '*'
            - resource: DBD
              member_name: 'IV*'
              time_stamp: '*'
            - resource: DBD
              member_name: 'SI*'
              time_stamp: '*'
            - resource: PSB
              member_name: 'AUT*'
              time_stamp: '*'
            - resource: PSB
              member_name: 'DBF*'
              time_stamp: '*'
            - resource: PSB
              member_name: 'DFH*'
              time_stamp: '*'
            - resource: PSB
              member_name: 'DFSI*'
              time_stamp: '*'
            - resource: PSB
              member_name: 'DFSS*'
              time_stamp: '*'
            - resource: PSB
              member_name: 'IP*'
              time_stamp: '*'
            - resource: PSB
              member_name: 'PG*'
              time_stamp: '*'
          managed_acbs: true

