---
- hosts: zsystem
  collections:
    - ibm.ibm_zos_ims
    - ibm.ibm_zos_core
  gather_facts: no
    
  environment: "{{ environment_vars }}"
    
  tasks:
    - name: test ims_catalog_populate
      ims_catalog_populate:
        mode: LOAD 
        acb_lib: [
          IMSTESTL.IMS1.ACBLIB
        ]
        reslib: [
          IMSTESTL.IMS1.SDFSRESL
        ]
        steplib: [
          IMSTESTL.IMS1.SDFSRESL
        ]
        proclib: [
          IMSTESTL.IMS1.PROCLIB
        ]
        dbd_lib: [
          IMSTESTL.IMS1.DBDLIB
        ]
        psb_lib: [
          IMSTESTL.IMS1.PSBLIB
        ]
        buffer_pool_param_dataset: "IMSTESTL.IMS1.PROCLIB(DFSVSMHP)"
        # primary_log_dataset:
        #   dataset_name: IMSTESTL.IMS1.LOG1
        #   disposition: NEW
        #   normal_disposition: DELETE
        #   record_format: FB
        #   record_length: 4092
        #   block_size: 4096
        #   primary: 100
        #   primary_unit: CYL
        #   secondary: 75
        #   secondary_unit: CYL
        #   type: SEQ
        # control_statements:
          # print_duplicate_resources: True
          # print_inserted_resources: False
          # managed_acbs:
            # update:
            #   replace_acb: UNCOND
            # stage: 
            #   save_acb: UNCOND
            #   clean_staging_dataset: true
            # setup: true
        # bootstrap_dataset:
        #   dataset_name: IMSTESTL.IMS1.DFSCD000.BSDS
        #   disposition: NEW
        #   normal_disposition: CATLG
        #   primary: 400
        # directory_datasets:
        #   - dataset_name: IMSTESTL.IMS1.DFSCD000.DI1001
        #     disposition: NEW
        #     normal_disposition: CATLG
        #     primary: 600
        #   - dataset_name: IMSTESTL.IMS1.DFSCD000.DI1002
        #     disposition: NEW
        #     normal_disposition: CATLG
        #     primary: 600
        #   - dataset_name: IMSTESTL.IMS1.DFSCD000.DI1003
        #     disposition: NEW
        #     normal_disposition: CATLG
        #     primary: 600
        # temp_acb_dataset:
        #   dataset_name: IMSTESTL.IMS1.ATEMP.TEST
        #   disposition: NEW
        #   normal_disposition: CATLG
        #   primary: 600
        # directory_staging_dataset:
        #   dataset_name: IMSTESTL.IMS1.DFSCD000.STG
        #   disposition: NEW
        #   normal_disposition: CATLG
        #   primary: 600
          

        
        