---
  - hosts: zsystem
    collections:
      - ibm.ibm_zos_ims
      - ibm.ibm_zos_core
    gather_facts: no
      
    environment: "{{ environment_vars }}"
      
    tasks:
      - name: test ims_catalog_populate
        command: dls -s IMSTESTL.IMS1.DFSCD000.BSDS
        register: response

      - debug:
          var: response